name: Fortify on Demand Scan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  FoD-SAST-Scan:
    # Use the appropriate runner for building your source code.
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1.2.2
        with:
          export-path: true
          fcli: latest

      - name: Create Application Release
        run: |
          # Login
          fcli fod session login --url ${{secrets.FOD_URL}} --client-id ${{secrets.FOD_CLIENT_ID}} --client-secret ${{secrets.FOD_CLIENT_SECRET}} -k
          # Create release
          fcli fod release create "${{ github.event.repository.name }}:${{ github.ref_name }}" --status Production --skip-if-exists --store rel
          fcli fod sast setup --release "::rel::" --assessment-type "Static Assessment" --frequency Subscription --entitlement-id ${{secrets.FOD_ENTITLEMENT_ID}} --technology-stack "Auto Detect" --audit-preference Automated --oss

      - name: Run FoD SAST Scan
        uses: fortify/github-action/fod-sast-scan@v1.2.2
        env:
          FOD_URL: ${{secrets.FOD_URL}}
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PASSWORD}}
          # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
          FOD_RELEASE: "${{ github.event.repository.name }}:${{ github.ref_name }}"
          EXTRA_PACKAGE_OPTS: -q -oss
          DO_WAIT: true
          # DO_EXPORT: true

      - name: Fortify Analysis summary
        run: |
          fcli fod session login --url ${{secrets.FOD_URL}} --client-id ${{secrets.FOD_CLIENT_ID}} --client-secret ${{secrets.FOD_CLIENT_SECRET}} -k
          fcli fod action run release-summary --release "${{ github.event.repository.name }}:${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

      - name: Fortify Security Gate
        run: |
          fcli fod session login --url ${{secrets.FOD_URL}} --client-id ${{secrets.FOD_CLIENT_ID}} --client-secret ${{secrets.FOD_CLIENT_SECRET}} -k
          fcli fod action run check-policy --rel "${{ github.event.repository.name }}:${{ github.ref_name }}"
